### ISSUE TITLE
Build fails due to precice not found

### ISSUE THREAD

**Issue by ajaust** [precice/fenics-adapter#39]
Hi,

I wonder whether I do something wrong or if I miss something. When I want to build the adapter it cannot find `precice` even though I have the bindings installed and working. I try to build the adapter from the `parallelFEniCS` branch.

When I change line 16 in `setup.py` to `install_requires=['fenics', 'scipy', 'numpy'],` it seems to work. However, the parallel test case fails, but I will open another issue for that. 

This is the error message:
```
Processing /home/jaustar/projects/fenics-precice-parallel/fenics-adapter
Collecting precice (from fenics-adapter==0.1)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/precice/
```

Issuing `ls ~/.local/lib/python3.6/site-packages/precice*` gives
```
/home/jaustar/.local/lib/python3.6/site-packages/precice.cpython-36m-x86_64-linux-gnu.so

/home/jaustar/.local/lib/python3.6/site-packages/precice-1.5.2-py3.6.egg-info:
PKG-INFO  SOURCES.txt  dependency_links.txt  requires.txt  top_level.txt
```

**Comment by positroncascade** [comment]
I am also having the same problem. How can I solve this?

**Comment by BenjaminRueth** [comment]
How did you install the [precice bindings](https://github.com/precice/precice/tree/develop/src/precice/bindings/python)? I have three possibilities in mind:

1. `python3 setup.py install`
2. `pip3 install --user .` (note the dot `.`)
3. `sudo pip3 install .` (note the dot `.`)

Option two is recommended for installing the bindings. If you installed the adapter using option 1 and 3, try uninstalling it and re-installing it using option 2.

[This Dockerfile](https://github.com/precice/systemtests/blob/add_fenics_test/Test_fe-fe.Ubuntu1804/Dockerfile) is used for testing the fenics-adapter and the heat-heat tutorial and might help you.

**Comment by positroncascade** [comment]
I wasn't able to download required precice files from pypi website but it might be just a network problem at that time. I fixed my problem.

**Comment by BenjaminRueth** [comment]
> 
> 
> I wasn't able to download required precice files from pypi website but it might be just a network problem at that time. I fixed my problem.

@positroncascade Providing preCICE (including the python bindings) via PyPI is for sure a future goal (see https://github.com/precice/precice/issues/436). Occasionally, we will also provide the fenics-adapter via PyPI. But this is a future goal and currently distribution of preCICE via PyPI is not working. 

Therefore, I currently cannot recommend you to use PyPI for getting preCICE and the python bindings. Please follow [our wiki](https://github.com/precice/precice/wiki#1-get-precice) for getting and building preCICE. 

Be aware that you will have to install the python bindings independently from this step. Instructions can be found [here](https://github.com/precice/precice/blob/develop/src/precice/bindings/python/README.md).

**Comment by ajaust** [comment]
Hi, 

I had finally time to check this out and it seems to work for me now. It seems to be a huge mess with `pip`. I normally used the one that I get via `apt-get` on Ubuntu. I played around with installing `pip` from the website and removing Ubuntu's `pip`. In the course of installing, removing and reinstalling software, I might have broken something on my system, but I could not find any problems yet, except that `pip3` does not work anymore. Therefore, I use `python3 -m pip` for calling `pip`. Moreover I upgraded to preCICE 1.6.0.

These are the steps that I did now:

Remove `pip` and reinstall `fenics` just to be sure as `fenics` pulls quite some python3 packages that I might have deinstalled
```bash
sudo apt-get remove python3-pip
sudo apt-get install --no-install-recommends fenics
```

Install `python_future` bindings and new `pip`
```bash
cd python_future
wget -q https://bootstrap.pypa.io/get-pip.py -O get-pip.py
sudo python3 get-pip.py
python3 -m pip install Cython mpi4py numpy enum34
python3 -m pip install --user .
python3 -c "import precice_future as precice"
```
There is no output. So it seems to work.

Install `python` bindings
```bash
cd ../python
python3 -m pip install --user .
python3 -c "import precice"
-c:1: Warning: This version of the precice bindings is deprecated and will be removed in preCICE version 2.0.0. You may import the updated python module using "import precice_future as precice" instead. Refer to the changelog for more information.
```
The warning indicates that it works.

I tested it with some of my code and it seems to work. However, I had to adapt my code. It called `set_mesh_vertices` with a list of points. However, the assertion in the precice bindings (see `precice.py`:61) fails as the list does not have any `size` property. Therefore, I converted the list into a `np.array`.

**Comment by BenjaminRueth** [comment]
> I had finally time to check this out and it seems to work for me now.

Glad to hear that the bindings are finally working. Do you think that there anything that we can do to improve the situation for future users?

Be aware that one of our goals for the next release it to distribute the bindings via pip: https://github.com/precice/precice/issues/436. I hope that this will avoid most of the trouble that you went through in https://github.com/precice/fenics-adapter/issues/39#issuecomment-534459519.

I am closing this issue, since the bindings are working for you now. If you think that there still need something to be fixed, feel free to reopen it again.
